mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('',include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('thoughts/', views.thotText.as_view(), name='thoughts'),
    path('thoughts/submit/', views.updateThoughtList, name='submit'),
    path('thoughts/list/', views.ThoughtListView.as_view(), name='list'),
]

polls/models.py
from django.db import models

# Create your models here.
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Thoughts(models.Model):
    thoughtText = models.TextField()

    def __str__(self):
        return self.thoughtText

polls/views.py
#from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, Thoughts

from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class thotText(generic.ListView):
    model = Thoughts
    template_name = 'polls/thoughts.html'

def updateThoughtList(request):
     # thought = get_object_or_404(Thoughts)
     # try:
     #     input_thought = thought.get(pk=request.POST['thought'])
     # except (KeyError, Thoughts.DoesNotExist):
     #     # Redisplay the question voting form.
     #     return render(request, 'polls/thoughts.html', {
     #         'error_message': "You didn't enter a thought."
     # })
     # else:
     #     input_thought.save()
     # return HttpResponseRedirect(reverse('polls:list'))
    try:
        submission = Thoughts(thoughtText=request.POST['thot'])
    except (KeyError, Thoughts.DoesNotExist):
        return render(request, 'polls/thoughts.html', {
            'error_message': "You didn't enter a thought."
        })
    else:
        submission.save()
    return HttpResponseRedirect(reverse('polls:list'))


class ThoughtListView(generic.ListView):
    model = Thoughts
    template_name = 'polls/list.html'
    context_object_name = 'latest_thought_list'

polls/templates/polls/detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">Polls App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'polls:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'polls:thoughts' %}">Thoughts</a>
    </div>
  </div>
</nav>

<h1 class="center downp uppad"> {{ question.question_text }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" class = "center" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}

    <div class="center downp uppad">
        <button type="submit" class="btn btn-dark">Vote</button>
    </div>
</form>

<footer class="page-footer font-small blue">
    <div class="footer-copyright text-center py-3">© 2021 Copyright: Muhammad Abdullah </div>
</footer>

polls/templates/polls/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">Polls App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'polls:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'polls:thoughts' %}">Thoughts</a>
    </div>
  </div>
</nav>

<h1 class="center downp uppad">Please select a poll! </h1>
    {% if latest_question_list %}

    <div class = "center">
      <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
      </ul>
    </div>
        {% else %}
    <p>No polls are available.</p>
    {% endif %}

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2021 Copyright: Muhammad Abdullah</div>
    </footer>

</body>

polls/templates/polls/list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
      xmlns:font-size="http://www.w3.org/1999/xhtml" xmlns:font-size="http://www.w3.org/1999/xhtml">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thoughts</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">Polls App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'polls:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'polls:thoughts' %}">Thoughts</a>
    </div>
  </div>
</nav>
    <h1 class="center downp uppad">Here's a list of all your thoughts! </h1>
    {% if latest_thought_list %}

        <table class="table table-dark table-bordered form-control-inline center ">
            {% for thought in latest_thought_list %}
            <tr class="center">
                <td class="center form-control-inline">{{ thought.thoughtText }}</td>
            </tr>
            {% endfor %}
        </table>

        <div class="center downp uppad">
            <a href="{% url 'polls:thoughts'%}">Another thought?</a>
        </div>

    {% endif %}

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2021 Copyright: Muhammad Abdullah
        </div>
    </footer>

</body>
</html>

polls/templates/polls/results.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">Polls App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'polls:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'polls:thoughts' %}">Thoughts</a>
    </div>
  </div>
</nav>

<h1 class="center downp uppad"> {{ question.question_text }} </h1>


<table class="table table-dark table-bordered form-control-inline2 center ">
            {% for choice in question.choice_set.all %}
            <tr class="center">
                <th> {{ choice.choice_text }} </th>
                <td class=""> {{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
            </tr>
            {% endfor %}
        </table>


<div class="center downp uppad">
            <a href="{% url 'polls:detail' question.id %}">Vote Again</a>
</div>

<footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2021 Copyright: Muhammad Abdullah
        </div>
</footer>

polls/templates/polls/thoughts.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
      xmlns:font-size="http://www.w3.org/1999/xhtml" xmlns:font-size="http://www.w3.org/1999/xhtml">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thoughts</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">Polls App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'polls:thoughts' %}">Thoughts</a>
    </div>
  </div>
</nav>
    <form action="submit/" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="form-group" >
            <h1 for="formGroupExampleInput" class="center downp uppad">Enter Thoughts: </h1>
            <div class = "center">
                <input type="text" class="form-control form-control-inline" id="formGroupExampleInput" placeholder="type..." name="thot">
            </div>
            <div class="center downp uppad"> <button type="submit" class="btn btn-dark">Submit</button> </div>
        </div>
    </form>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2021 Copyright: Muhammad Abdullah
        </div>
    </footer>

</body>
</html>